### ISSUE TITLE
Basic Keyboard Functions Missing 

### ISSUE THREAD

**Issue by ArchBlood** [humhub/app#186] opened 2024-05-27 16:04 UTC
It seems after testing the latest version of the app that many things aren't working now, namely the ability to use native `cut` and deleting of highlighted text.

I've tested this in the default Gboard against other apps and even browsers where a `cut` option shows on highlighted text which there are none in the latest version, even deleting highlighted text is impossible.

**Comment by luke-** [comment] 2024-05-27 16:25
@marc-farre Can you please check?

**Comment by ArchBlood** [comment] 2024-05-27 16:47
I'd like to mention that I had the issue when mentioning someone.

**Comment by marc-farre** [comment] 2024-05-28 08:25
@ArchBlood I cannot reproduce the issue with the native cut and deleting of highlighted text.

Tested (HumHub 10.16 develop branch, App v10.100), creating a new post:
- Android 10 (Huawei P30 pro), Microsoft SwiftKey keyboard
- Idem, but with Gboard keyboard (latest version)
- Android 13 (Samsung S20), Samsung Keyboard

![image](https://github.com/humhub/app/assets/23310825/519967bb-5a55-497b-9e3a-03a19b6f9994)

Can you provide more info about your device and a screenshot? Thanks!

**Comment by marc-farre** [comment] 2024-05-28 08:30
> when mentioning someone.

Tested also: I cannot select the mentioned user, but I can select other the text before and after:

![image](https://github.com/humhub/app/assets/23310825/4642a1c4-b128-4772-8c50-cb1fc035bcb0)

When pasting, the mentioned user is not pasted, but the text before and after yes.

**Comment by marc-farre** [comment] 2024-05-28 08:50
Maybe related to https://github.com/humhub/app/issues/187

**Comment by luke-** [comment] 2024-05-28 09:50
@marc-farre Thanks.

I'll close this and it's linked now with #187

**Closed by luke-** 2024-05-28 09:50 UTC
Labels: Need Investigation

**Comment by ArchBlood** [comment] 2024-05-28 12:20
I've only been able to reproduce on Android 12 with Gboard.
![Screenshot_20240528-081924.png](https://github.com/humhub/app/assets/35392110/a59f4fac-a045-43e7-b6b2-7da04cc8cbc8)

![Screenshot_20240528-081907.png](https://github.com/humhub/app/assets/35392110/cd02e888-a9be-4ef5-a1c1-0845c5d5e636)

**Comment by marc-farre** [comment] 2024-05-28 12:55
@ArchBlood Thanks. I cannot reproduce on my devices, but the bug exists.
However, I suggest to first resolve https://github.com/humhub/app/issues/187 and then see if this issue persists.
